# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

dist: trusty
sudo: required
language: R
sudo: false
cache: packages

addons:
  apt:
    packages:
      - ant
      - libv8-dev

#install:
#  - Rscript -e 'install.packages(c("devtools", "jsonvalidate", "roxygen2", "testthat", "curl", "digest", "ggplot2",  "gtools", "jsonlite", "knitr", "provSummarizeR", "provViz", "rmarkdown", "sessioninfo", "stringi", "XML"))'
#  - Rscript -e 'print (installed.packages())'

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

script:
  - Rscript -e 'print (installed.packages())'
  - Rscript -e "devtools::check()" 
  - Rscript -e "devtools::install()" 
  - ant -file tests.xml test-travis-rdtLite

notifications:
  slack: endtoendprovenance:WxevOs6n66eZRbCn9HcW2mGD
