---
title: "Genus"
author: "Tess McCabe"
date: "April 24, 2015"
output: html_document
---

NOTE: You may have to re-load this page if you are loading thr setup from the other R-markdown files, because some of the object names are the same. 


```{r}
#### Packages
library(permute)
library(lattice)
library(vegan)
library(vegetarian)
library(car)
#Note that a package not published on the CRAN server "biostats.r" is sourced later. For more information please contact Kevin McGarigal of the University of Massachusetts, Amherst

#### Read in Data 
setwd("/Users/tessmccabe/Dropbox/Junior/Junior Year research/Ant Stats/data") #Set to appropriate local working directory
source('biostats.R')
antdatanum<-read.csv("ants.csv") 
```

Sort into Genus
```{r}
antdatanum$Aphpic<-antdatanum$Aphpic+antdatanum$Aphrud+antdatanum$Aphful #Combine both Aphpic and Aphrud 
antdatanum<-antdatanum[,-c(4,6)] # nix aphrud

antdatanum$Camnov<-antdatanum$Camnov+antdatanum$Campen #Combine both Camnov and Campen
antdatanum<-antdatanum[,-c(6)] #Nix campen

antdatanum$Forase<-antdatanum$Forase+antdatanum$Forneo+antdatanum$Forrub+antdatanum$Forsubi+antdatanum$Forsub #Same for For
antdatanum<-antdatanum[,-c(7:10)] #Nix 

antdatanum$Lasali<-antdatanum$Lasali+antdatanum$Lasumb #Same for Las
antdatanum<-antdatanum[,-c(8)] #Nix 

antdatanum$Mryame<-antdatanum$Mryame+antdatanum$Myrpun #Same for myr
antdatanum<-antdatanum[,-c(9)] #Nix 

antdata2 <- antdatanum[,-c(1:3)]#Create a matrix without lable columns
antdata2[antdata2>0] <-1 #Make that matrix presence vs absence change all numbers into 1's. 
antdata3<-cbind(antdatanum[,1:3],antdata2)

#Now let's look at the values
plot(antdatanum2)
antdatanum2<-antdatanum[,-c(1:3)]
as.matrix(antdatanum2)
plot(antdatanum2~antdatanum$Treatment)
boxplot(antdatanum2)
#Jenky way to get around this problem. 
tn1<-antdata2[antdata3$Treatment=='1',]
tn2<-antdata2[antdata3$Treatment=='2',]
tn3<-antdata2[antdata3$Treatment=='3',]
tn4<-antdata2[antdata3$Treatment=='4',]
boxplot(c(tn1,tn3))
```