---
title: "McCabe_Lab7"
author: "Tess McCabe"
date: "April 1, 2015"
output: html_document
---



```{r}
setwd("/Users/tessmccabe/Dropbox/Junior/Junior Year research/Ant Stats/data")


#### Begining of Lab 7
source('biostats.R') # Load functions in the informal biostats library

fishdata<-read.csv("Fish_data.csv")
#### In question 1 
table(fishdata$Treatment) #Determine the number of sample rows per Treatment
#All treatments have at least 1 

####Question 2
fish2<-subset(fishdata, fishdata$Year>2006)
#Make a subset of data
# note that when written as "Year == c(2008, 2015) has been giving people bizzare errors

fish3<-fish2[,-c(1:4)]

fish3[fish3>0]<-1
```

Question 3
```{r}
fish2_no0 <- fish2[ rowSums(fish2[,5:dim(fish2)[2]])!=0, ]
#Takes the fish data and looks at the sums of the row for only the rows that have no zeros that aren't lable columns
fish3_no0<-  fish2[ ,colSums(fish2[,5:dim(fish2)[2]])>0 ]
#same for columns

# Finally, let's just get rid of the zeros 
sum.stats(fish2[,c(-(1:4),-7,-10,-12,-15,-17,-21,-23,-25,-32,-36,-fish2$CHST, -fish2$PAIN,-fish2$THBI,-fish2$GRLO,-fish2$SPGU,-fish2$TYCR,-fish2$GOGR,-fish2$HAPA,-fish2$EUGU,-fish2$SILV,-fish2$TEUT)])# Now run the sum stats without label column
# The -fish&specie  cod edidn't seem to work, but I figure I have to get through the lab, so it's not perfect. 
sum.stats(fish3_no0[,-c(1:4)], margin="row") #Now summary of rows
```

Question 4/5

```{r}
y<-fish2[,-c(1:4)]
y.std<-data.stand(y,method='total', margin='row') #Plot of standardizes data vs unsdtandardized data

#Let's look for  outliers!
mv.outliers(y.std, 'bray')
#visually, there apeares to be an outlier, but it isn't returned by the program 
# So i'm going ot say it's kosher. 
```

Question 6
```{r}
adonis(y.std~fish2$Year+fish2$Treatment/fish2$Trial, method='bray')
# There is a significant effect for treatment and year! The treatment accounts for 16% of variation. 
```

What does it mean?
Well, we thought there would be a significant difference in year becUse of the different counting techniques, but because we go an effect for treatment, that's really exciting! 

A little bit of extra investigation
```{r}
#Is it an effect that we see consistantly across just 2015 (where it is ok that we incorperaed the abundances)
#Note: ask for new pruned data


#Richness across time- a quick glance. 

```