*Tess This is your attempt at adapting the 2015 SWaN analysis to your HF Simes summer 2015 data. Enjoy*



**Packages & Data**

```{r}
#### Packages
library(permute)
library(lattice)
library(vegan)
library(vegetarian)
library(car)
library(reshape)
#Note that a package not published on the CRAN server "biostats.r" is sourced later. For more information please contact Kevin McGarigal of the University of Massachusetts, Amherst

#### Read in Data 
setwd("/Users/tessmccabe/Dropbox/Harvard Forest/R-code") #Set to appropriate local working directory
source('biostats.R')
ants<-read.csv("data.csv") #



###
ants$abundance[is.na(ants$abundance)==TRUE]<-1 #Change 2007's NA's into occurences
ants2<-ants[,-c(2,3,6,7,8,9,10,13)]#Cut out vars that I don't want, and makes sure I don't have NAs
ants3<-reshape(ants2, timevar= "code", idvar=c("year","plot","treatment"), direction="wide")
#ants3 <-melt(antsTest, measure.vars=c(as.factor("code"),as.factor("abundance"))) #Reshape data
ants3[is.na(ants3)==TRUE] <-0# Make the NA's zeros
ants4<-ants3[,-c(1:3)] #get out lable columbs
ants4[ants4>0]<-1 #Make presence vs absence
ants5<-cbind(ants3[1:3],ants4)
```

**Figures & Discriptive Statistics**

```{r, echo=FALSE}
#### Species Occurences 
ants4Plot<-(colSums(ants4)) #a vector of the sum of every column
par(mar=(c(10, 4, 4, 2) + 0.1))# Set margins for barplot
barplot(ants4Plot, ylab= "Occurrence", names.arg= names(ants4), las=3, cex.names=0.8, main="Species Occurence")
par(mar=(c(5, 4, 4, 2) + 0.1)) #Reset paramaters for other figures 
#Plot of Species Occurences

#### Species Richness by Year
specRichYear3<-rowSums(ants5[ants5$year=="2003",-c(1:3)])
specRichYear4<-rowSums(ants5[ants5$year=="2004",-c(1:3)])
specRichYear5<-rowSums(ants5[ants5$year=="2005",-c(1:3)])
specRichYear6<-rowSums(ants5[ants5$year=="2006",-c(1:3)])
specRichYear8<-rowSums(ants5[ants5$year=="2008",-c(1:3)])
specRichYear7<-rowSums(ants5[ants5$year=="2007",-c(1:3)])
specRichYear9<-rowSums(ants5[ants5$year=="2009",-c(1:3)])
specRichYear10<-rowSums(ants5[ants5$year=="2010",-c(1:3)])
specRichYear11<-rowSums(ants5[ants5$year=="2011",-c(1:3)])
specRichYear12<-rowSums(ants5[ants5$year=="2012",-c(1:3)])
specRichYear13<-rowSums(ants5[ants5$year=="2013",-c(1:3)])
specRichYear14<-rowSums(ants5[ants5$year=="2014",-c(1:3)])

sdyear<-c(sd(specRichYear3),
          sd(specRichYear4),
          sd(specRichYear5),
          sd(specRichYear6),
          sd(specRichYear7),
          sd(specRichYear8),
          sd(specRichYear9),
          sd(specRichYear10),
          sd(specRichYear11),
          sd(specRichYear12),
          sd(specRichYear13),
          sd(specRichYear14))#Vector of standard deveations
barplot(c(mean(specRichYear3), mean(specRichYear4), mean(specRichYear5),mean(specRichYear6),mean(specRichYear7),mean(specRichYear8), mean(specRichYear9),mean(specRichYear10),mean(specRichYear11),mean(specRichYear12),mean(specRichYear13),mean(specRichYear14)), names.arg= c("2003","2004","2005", "2006","2007", "2008","2009","2010","2011","2012","2013","2014"), ylab="Average Species Richness", main= "Species Richness by Year") #Displays the mean number of species per year


#### Species Richness by Treatment
specRichTreat1<-rowSums(ants5[ants5$treatment=="HemlockControl",-c(1:3)])
specRichTreat2<-rowSums(ants5[ants5$treatment=="Girdled",-c(1:3)])
specRichTreat3<-rowSums(ants5[ants5$treatment=="Logged",-c(1:3)])
specRichTreat4<-rowSums(ants5[ants5$treatment=="HardwoodControl",-c(1:3)])

sdtreat<-c(sd(specRichTreat1),sd(specRichTreat2),sd(specRichTreat3),sd(specRichTreat4))# Vector of standard deveations

barplot(c(mean(specRichTreat1),mean(specRichTreat2),mean(specRichTreat3),mean(specRichTreat4)), names.arg= c("Hemlock Control", "Girdled", "Logged","Hardwood Control"), ylab="Average Species Richness", main= "Species Richness by Treatment", col=c("purple","orange","blue", "green"))#Displays the mean number of species per treatment 
```


**Statistical Tests**

Part one: Multivariate Analysis 
```{r}
#### Manova
rowZero<-ants5[(rowSums(ants5[,-c(1:3)])!=0),]# Check for and remove any rows without any species found. 
rowZero2<-rowZero[rowZero$year!="2003",]
rowZero2<-rowZero[rowZero$year!="2004",]# Removes 2003 & 2004, which I assume is the control year. 
mv.outliers(rowZero2[,-c(1:3)], method='bray')# Returns outliers. From now on nix rows 1743 (62) and 2368 (76)
rowZero2<-rowZero2[-c(62,76),] #Nix outliers
mv.outliers(rowZero2[,-c(1:3)], method='bray')# Check again for no outliers
adonis(rowZero2[,-c(1:3)]~(rowZero2$treatment/rowZero2$plot)*rowZero2$year, method='bray')# Found significant difference between Year, Treatment, Treatment vs Plot, Treatment vs Year, but not all three terms.  


### Visual Confirmation of Manova results  PCoA
treat<-rowZero2$treatment
year<-rowZero2$year
plot<-rowZero2$plot
yearBeta<-betadisper(vegdist(rowZero2[,-c(1:3)], method= 'bray'), group= year, type=c("median","centroid")) #Creates a betadisper object useing a vector of bray distance measures  grouped by year
treatBeta<-betadisper(vegdist(rowZero2[,-c(1:3)], method= 'bray'), group= treat, type=c("median","centroid")) #Creates a similar betadisper object grouped by treatment
plotBeta<-betadisper(vegdist(rowZero2[,-c(1:3)], method= 'bray'), group= plot, type=c("median","centroid"))
plotYear<-plot(yearBeta, axes = c(1,2), cex = 0.7, hull = TRUE, main= "Year Visualization",col=c("red","blue","purple","green"))

plot(treatBeta, axes = c(1,2), cex = 0.7, hull = TRUE, main= "Treatment Visualization") 

#This is neat. It looks like a treatment gradient. It also looks like a clear distinction between a group of years. 

### Pairwise Comparisons of years
permutest(yearBeta, pairwise =TRUE,control = how(nperm = 999)) #Sig between 2013 & 2007, 2012 &2007, 2003 &2003, 2005 &2007, 2006 & 2007. 

permutest(treatBeta, pairwise =TRUE,control = how(nperm = 999)) #No pairwise significance. Weird. 

nmds.scree(rowZero[,-c(1:3)], distance='bray', k=6, trymax=50, autotransform=FALSE)# Based on this, 5 axes has has 0.06 percent stress, and 6 has 0.03 percent stress. I'm going with 6 axis. 
Ant_nmds <- metaMDS(rowZero[,-c(1:3)], distance='bray', k=6, trymax=50, autotransform=FALSE)
stressplot(Ant_nmds) #The fit is still good. 
grp <- rowZero$treatment
p <- ordiplot(Ant_nmds, choices=c(1,2), display='sites', main= "Treatment")

ordihull(p, groups=grp, col='blue', show.groups="HemlockControl") 
ordihull(p, groups=grp, col='red', show.groups="Girdled") 
ordihull(p, groups=grp, col='green', show.groups="Logged") 
ordihull(p, groups=grp, col='purple', show.groups="HardwoodControl") 
#almost no diferentiation
###adding in a legend 
#legend2<- c("2003-2004 (Control)","2005-2010", "2011-2014")
#legend(-2, y =-0.7, legend=legend1,border = "white", fill=c('blue','red', 'green', 'purple'),cex=0.75)
l<- ordiplot(Ant_nmds, choices=c(1,2), display='sites', main= "Year")
#legend1<- c("Hemlock Control","Girdled", "Logged","Hardwood Control")
#legend(-2, y =-0.5, legend=legend2,border = "white", fill=c('blue','gray', 'red'))
grp2<-rowZero$year
ordihull(p, groups=grp2, col='blue', show.groups="2003") 
ordihull(p, groups=grp2, col='blue', show.groups="2004") 
ordihull(p, groups=grp2, col='gray81', show.groups="2005") 
ordihull(p, groups=grp2, col='gray76', show.groups="2006")
ordihull(p, groups=grp2, col='gray76', show.groups="2007")
ordihull(p, groups=grp2, col='gray71', show.groups="2008") #all of them overlap with the control. 
ordihull(p, groups=grp2, col='gray66', show.groups="2009")
ordihull(p, groups=grp2, col='gray61', show.groups="2010") 
ordihull(p, groups=grp2, col='red', show.groups="2011")
ordihull(p, groups=grp2, col='red', show.groups="2012") 
ordihull(p, groups=grp2, col='red', show.groups="2013") 
ordihull(p, groups=grp2, col='red', show.groups="2014") 
```

Time Breakdown NMDS'
```{r}
#### why does this even have an error? This should be simple. 
hat<-subset(rowZero, rowZero$year==c("2005","2006","2007"))

nmds.scree(hat, distance='bray', k=6, trymax=50, autotransform=FALSE)# Based on this, 5 axes has has 0.06 percent stress, and 6 has 0.03 percent stress. I'm going with 6 axis. 
Ant_nmds2 <- metaMDS(hat, distance='bray', k=2, trymax=50, autotransform=FALSE)

grp <- hat$treatment
m <- ordiplot(Ant_nmds2, choices=c(1,2), display='sites', main= "Treatment")

ordihull(m, groups=grp, col='blue', show.groups="HemlockControl") 
ordihull(m, groups=grp, col='red', show.groups="Girdled") 
ordihull(m, groups=grp, col='green', show.groups="Logged") 
ordihull(m, groups=grp, col='purple', show.groups="HardwoodControl") 

Ant_nmds3 <- metaMDS(rowZero[,-c(1:3)], distance='bray', k=6, trymax=50, autotransform=FALSE)

grp <- rowZero$treatment
n <- ordiplot(Ant_nmds3, choices=c(1,2), display='sites', main= "Treatment")

ordihull(n, groups=grp, col='blue', show.groups="HemlockControl") 
ordihull(n, groups=grp, col='red', show.groups="Girdled") 
ordihull(n, groups=grp, col='green', show.groups="Logged") 
ordihull(n, groups=grp, col='purple', show.groups="HardwoodControl") 

Ant_nmds4 <- metaMDS(rowZero[,-c(1:3)], distance='bray', k=6, trymax=50, autotransform=FALSE)

grp <- rowZero$treatment
o <- ordiplot(Ant_nmds, choices=c(1,2), display='sites', main= "Treatment")

ordihull(o, groups=grp, col='blue', show.groups="HemlockControl") 
ordihull(o, groups=grp, col='red', show.groups="Girdled") 
ordihull(o, groups=grp, col='green', show.groups="Logged") 
ordihull(o, groups=grp, col='purple', show.groups="HardwoodControl") 


```




Univariate Analysis

```{r}
rowZeroNum<-ants5[(rowSums(ants5[,-c(1:3)])!=0),] # I included the control years in this. Is this apropriate? 
rich<-rowSums(rowZeroNum[,-c(1:3)])
rich_aov<-aov(rich~rowZeroNum$treatment*as.factor(rowZeroNum$year))

plot(resid(rich_aov)) # Plot siduals to double check normality. Appears normal. 
Anova(rich_aov) #Treatment is most significant, thenyear, then interaction. 
TukeyHSD(rich_aov) #this is a lot of information not really sure if it's worth it. 

```

Check of control years 2003 & 2004
```{r}
think<-ants5[ants5=="2003",]
dink<-ants5[ants5=="2004",]
ants4Con<-rbind(think,dink)
rowZero2006<-ants4Con[(rowSums(ants4Con[,-c(1:3)])!=0),]
rich2006<-rowSums(rowZero2006[,-c(1:3)])

aov2006<-aov(rich2006~as.factor(rowZero2006$treatment))
Anova(aov2006)
TukeyHSD(aov2006) 
#There is a significant difference in treatment even in control years. Hmmmmmmm
#HardControl and girdled 
#Hem and hard
#Logged and Hard (Not as much though)

```


Adjusted p-values (As of 7/23/15 not edited from old 2014 code)
```{r}
p.vals<-c(0.422,0.004,0.996,0.712, 0.724,0.49325,0.05188,0.67472,0.2024) #P values from  1st adonis (5 vals), from univatiate analysis (3 vals), and also from that one 2006 Anova. 
p.adjust(p.vals) #Now year is significant in the manova, but not in the anova. 

p.vals2<-c(0.384,0.001,0.515,0.847, 0.020,0.49325,0.05188,0.67472,9.0347e-02,1.1967e-01,5.1445e-06,1.8390e-01,2.8814e-01,5.6595e-05,0.2024) # Edited to include the permutation values (6 vals) and the univariete check of 2006 (1val)
p.adjust(p.vals2) #MANOVA still significant, permutation values show a difference between 2009 & 2008 as well as a differnece between 2008 & 2007. 
```
